# Generated by Django 5.2.12 on 2026-03-10 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('curriculum', '0001_initial'),
        ('enrollments', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_carnet', models.CharField(blank=True, max_length=20, verbose_name='Carné')),
                ('uc_code', models.CharField(blank=True, max_length=30, verbose_name='Código UC')),
                ('uc_name', models.CharField(blank=True, max_length=300, verbose_name='Nombre UC')),
                ('uc_credits', models.PositiveIntegerField(default=0, verbose_name='Créditos UC')),
                ('period_name', models.CharField(blank=True, max_length=100, verbose_name='Período')),
                ('partial1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Parcial 1')),
                ('partial2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Parcial 2')),
                ('partial3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Parcial 3')),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota final')),
                ('status', models.CharField(choices=[('in_progress', 'En progreso'), ('passed', 'Aprobado'), ('failed', 'Reprobado'), ('incomplete', 'Incompleto'), ('withdrawn', 'Retirado')], default='in_progress', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curricular_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='curriculum.curricularunit', verbose_name='Unidad Curricular')),
                ('enrollment_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='enrollments.enrollmentdetail', verbose_name='Detalle de inscripción')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='courses.period', verbose_name='Período')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='courses.section', verbose_name='Sección')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'ordering': ['-period', 'student_carnet'],
                'unique_together': {('student', 'section', 'period')},
            },
        ),
    ]
