# Generated by Django 4.2 on 2026-03-02 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(verbose_name='ID de estudiante')),
                ('course_id', models.IntegerField(verbose_name='ID de curso')),
                ('section_id', models.IntegerField(verbose_name='ID de sección')),
                ('period_id', models.IntegerField(verbose_name='ID de período')),
                ('enrollment_detail_id', models.IntegerField(verbose_name='ID de detalle de inscripción')),
                ('student_carnet', models.CharField(blank=True, max_length=20, verbose_name='Carné')),
                ('course_code', models.CharField(blank=True, max_length=20, verbose_name='Código del curso')),
                ('course_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre del curso')),
                ('period_name', models.CharField(blank=True, max_length=50, verbose_name='Período')),
                ('partial1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Parcial 1')),
                ('partial2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Parcial 2')),
                ('partial3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Parcial 3')),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota final')),
                ('status', models.CharField(choices=[('in_progress', 'En progreso'), ('passed', 'Aprobado'), ('failed', 'Reprobado'), ('incomplete', 'Incompleto'), ('withdrawn', 'Retirado')], default='in_progress', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'ordering': ['-period_id', 'student_carnet'],
                'unique_together': {('student_id', 'section_id', 'period_id')},
            },
        ),
    ]
