# Generated by Django 4.2 on 2026-03-02 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la carrera')),
                ('faculty', models.CharField(max_length=200, verbose_name='Facultad')),
                ('department', models.CharField(blank=True, max_length=200, verbose_name='Departamento')),
                ('duration_semesters', models.PositiveIntegerField(default=10, verbose_name='Duración (semestres)')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True, verbose_name='ID de usuario (Auth Service)')),
                ('carnet', models.CharField(max_length=20, unique=True, verbose_name='Carné')),
                ('semester', models.PositiveIntegerField(default=1, verbose_name='Semestre actual')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('graduated', 'Egresado'), ('suspended', 'Suspendido'), ('withdrawn', 'Retirado')], default='active', max_length=20, verbose_name='Estado')),
                ('enrollment_date', models.DateField(verbose_name='Fecha de ingreso')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('national_id', models.CharField(blank=True, max_length=20, verbose_name='DPI/Cédula')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.career', verbose_name='Carrera')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['carnet'],
            },
        ),
    ]
