# Generated by Django 4.2 on 2026-03-02 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(verbose_name='ID de estudiante')),
                ('period_id', models.IntegerField(verbose_name='ID de período')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inscripción')),
                ('status', models.CharField(choices=[('enrolled', 'Inscrito'), ('withdrawn', 'Retirado'), ('completed', 'Completado')], default='enrolled', max_length=20, verbose_name='Estado')),
                ('student_carnet', models.CharField(blank=True, max_length=20, verbose_name='Carné del estudiante')),
                ('period_name', models.CharField(blank=True, max_length=50, verbose_name='Nombre del período')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['-enrollment_date'],
                'unique_together': {('student_id', 'period_id')},
            },
        ),
        migrations.CreateModel(
            name='EnrollmentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.IntegerField(verbose_name='ID de sección')),
                ('course_id', models.IntegerField(verbose_name='ID de curso')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('withdrawn', 'Retirado')], default='active', max_length=20, verbose_name='Estado')),
                ('course_code', models.CharField(blank=True, max_length=20, verbose_name='Código del curso')),
                ('course_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre del curso')),
                ('section_number', models.CharField(blank=True, max_length=10, verbose_name='Número de sección')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de retiro')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='enrollments.enrollment', verbose_name='Inscripción')),
            ],
            options={
                'verbose_name': 'Detalle de inscripción',
                'verbose_name_plural': 'Detalles de inscripción',
                'unique_together': {('enrollment', 'section_id')},
            },
        ),
    ]
