# Generated by Django 5.2.12 on 2026-03-10 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('curriculum', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inscripción')),
                ('status', models.CharField(choices=[('enrolled', 'Inscrito'), ('withdrawn', 'Retirado'), ('completed', 'Completado')], default='enrolled', max_length=20, verbose_name='Estado')),
                ('student_carnet', models.CharField(blank=True, max_length=20, verbose_name='Carné del estudiante')),
                ('period_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre del período')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.period', verbose_name='Período')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['-enrollment_date'],
                'unique_together': {('student', 'period')},
            },
        ),
        migrations.CreateModel(
            name='EnrollmentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('withdrawn', 'Retirado')], default='active', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de retiro')),
                ('uc_code', models.CharField(blank=True, max_length=30, verbose_name='Código UC')),
                ('uc_name', models.CharField(blank=True, max_length=300, verbose_name='Nombre UC')),
                ('uc_credits', models.PositiveIntegerField(default=0, verbose_name='Créditos')),
                ('section_number', models.CharField(blank=True, max_length=10, verbose_name='Número de sección')),
                ('career_name', models.CharField(blank=True, max_length=300, verbose_name='Carrera')),
                ('professor_name', models.CharField(blank=True, max_length=200, verbose_name='Profesor')),
                ('curricular_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_details', to='curriculum.curricularunit', verbose_name='Unidad Curricular')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='enrollments.enrollment', verbose_name='Inscripción')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_details', to='courses.section', verbose_name='Sección')),
            ],
            options={
                'verbose_name': 'Detalle de inscripción',
                'verbose_name_plural': 'Detalles de inscripción',
                'unique_together': {('enrollment', 'section')},
            },
        ),
    ]
