# Generated by Django 4.2 on 2026-03-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_refactor_enrollmentdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='period_id',
            field=models.IntegerField(db_index=True, verbose_name='ID de período'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student_id',
            field=models.IntegerField(db_index=True, verbose_name='ID de estudiante'),
        ),
        migrations.AlterField(
            model_name='enrollmentdetail',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('withdrawn', 'Retirado')], default='active', max_length=20),
        ),
    ]
