# Generated by Django 5.2.12 on 2026-03-10 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('curriculum', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Lapso I 2026-I', max_length=100, unique=True, verbose_name='Nombre del período')),
                ('period_type', models.CharField(choices=[('lapso_i', 'Lapso I'), ('lapso_ii', 'Lapso II'), ('intensivo', 'Intensivo de Verano')], default='lapso_i', max_length=20, verbose_name='Tipo de período')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de fin')),
                ('is_active', models.BooleanField(default=False, verbose_name='Período activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Período académico',
                'verbose_name_plural': 'Períodos académicos',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.CharField(help_text='Ej: A, B, 01', max_length=10, verbose_name='Número / letra de sección')),
                ('professor_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre del profesor (denormalizado)')),
                ('schedule', models.CharField(blank=True, help_text='Ej: Lun-Mié 07:00–09:00', max_length=200, verbose_name='Horario')),
                ('classroom', models.CharField(blank=True, max_length=100, verbose_name='Aula')),
                ('max_students', models.PositiveIntegerField(default=30, verbose_name='Cupo máximo')),
                ('enrolled_count', models.PositiveIntegerField(default=0, verbose_name='Inscritos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('uc_code', models.CharField(blank=True, max_length=30, verbose_name='Código UC')),
                ('uc_name', models.CharField(blank=True, max_length=300, verbose_name='Nombre UC')),
                ('uc_credits', models.PositiveIntegerField(default=0, verbose_name='Créditos UC')),
                ('career_name', models.CharField(blank=True, max_length=300, verbose_name='Carrera')),
                ('sede_name', models.CharField(blank=True, max_length=200, verbose_name='Sede')),
                ('nucleo_name', models.CharField(blank=True, max_length=200, verbose_name='Núcleo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='students.career', verbose_name='Carrera')),
                ('curricular_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='curriculum.curricularunit', verbose_name='Unidad Curricular')),
                ('nucleo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='core.nucleo', verbose_name='Núcleo (opcional)')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.period', verbose_name='Período académico')),
                ('professor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections_taught', to=settings.AUTH_USER_MODEL, verbose_name='Profesor asignado')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.sede', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'ordering': ['period', 'uc_code', 'section_number'],
                'unique_together': {('curricular_unit', 'career', 'period', 'sede', 'section_number')},
            },
        ),
        migrations.CreateModel(
            name='SectionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Lunes'), ('TUE', 'Martes'), ('WED', 'Miércoles'), ('THU', 'Jueves'), ('FRI', 'Viernes'), ('SAT', 'Sábado')], max_length=3)),
                ('start_time', models.TimeField(verbose_name='Hora inicio')),
                ('end_time', models.TimeField(verbose_name='Hora fin')),
                ('classroom', models.CharField(blank=True, max_length=100, verbose_name='Aula')),
                ('session_type', models.CharField(choices=[('theory', 'Teórico'), ('practice', 'Práctico'), ('lab', 'Laboratorio'), ('virtual', 'Virtual'), ('hybrid', 'Híbrido')], default='theory', max_length=10, verbose_name='Tipo de sesión')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='courses.section')),
            ],
            options={
                'verbose_name': 'Horario de Sección',
                'verbose_name_plural': 'Horarios de Sección',
                'ordering': ['day', 'start_time'],
            },
        ),
    ]
