# Generated by Django 4.2 on 2026-03-02 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del curso')),
                ('credits', models.PositiveIntegerField(default=3, verbose_name='Créditos')),
                ('department', models.CharField(max_length=200, verbose_name='Departamento')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prerequisites', models.ManyToManyField(blank=True, to='courses.course', verbose_name='Prerrequisitos')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Período')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de fin')),
                ('is_active', models.BooleanField(default=False, verbose_name='Período activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Período académico',
                'verbose_name_plural': 'Períodos académicos',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.CharField(max_length=10, verbose_name='Sección')),
                ('professor_name', models.CharField(max_length=200, verbose_name='Nombre del profesor')),
                ('schedule', models.CharField(help_text='Ej: Lun-Mie 7:00-9:00', max_length=200, verbose_name='Horario')),
                ('classroom', models.CharField(blank=True, max_length=50, verbose_name='Aula')),
                ('max_students', models.PositiveIntegerField(default=30, verbose_name='Cupo máximo')),
                ('enrolled_count', models.PositiveIntegerField(default=0, verbose_name='Inscritos')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.course', verbose_name='Curso')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.period', verbose_name='Período')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'ordering': ['course__code', 'section_number'],
                'unique_together': {('course', 'period', 'section_number')},
            },
        ),
    ]
