# Generated by Django 4.2 on 2026-03-09 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_section_add_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.period', verbose_name='Período académico'),
        ),
    ]
