# Generated by Django 4.2 on 2026-03-02 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurricularUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Código institucional (ej: UC-CFD-001). Se auto-genera si queda vacío.', max_length=20, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('component', models.CharField(choices=[('CFPE', 'Formación Profesional Específico'), ('CFD', 'Formación Docente'), ('CFC', 'Formación Contextualizado'), ('ECU', 'Eje Curricular')], max_length=10)),
                ('uc_type', models.CharField(choices=[('UNCO', 'Obligatoria'), ('UNCLE', 'Libre Elección')], default='UNCO', max_length=10, verbose_name='Tipo')),
                ('level', models.CharField(blank=True, choices=[('FUND', 'Fundamentación'), ('INTEG', 'Integración'), ('PROF', 'Profundización'), ('', 'No especificado')], max_length=10, verbose_name='Nivel')),
                ('area', models.CharField(blank=True, help_text='Área temática (ej: Formación Ciudadana)', max_length=200)),
                ('credits', models.PositiveIntegerField(default=4, verbose_name='Créditos (CA)')),
                ('teaching_hours', models.PositiveIntegerField(default=4, verbose_name='Horas Docente (HAD)')),
                ('student_hours', models.PositiveIntegerField(default=8, verbose_name='Horas Estudiante (HLE)')),
                ('is_exit_req', models.BooleanField(default=False, verbose_name='Requisito de Egreso (AE/SC)')),
                ('description', models.TextField(blank=True, verbose_name='Descripción / Fundamentación')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unidad Curricular',
                'verbose_name_plural': 'Unidades Curriculares',
                'ordering': ['component', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CareerSede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_id', models.IntegerField(db_index=True, help_text='ID Carrera (students_service)')),
                ('sede_id', models.IntegerField(db_index=True, help_text='ID Sede (auth_service)')),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by_id', models.IntegerField(blank=True, help_text='ID del usuario global que realizó la asignación (auth_service)', null=True)),
            ],
            options={
                'verbose_name': 'Carrera en Sede',
                'verbose_name_plural': 'Carreras por Sede',
                'ordering': ['career_id', 'sede_id'],
                'unique_together': {('career_id', 'sede_id')},
            },
        ),
        migrations.CreateModel(
            name='CareerPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_id', models.IntegerField(db_index=True, help_text='ID de la Carrera en students_service')),
                ('academic_period', models.PositiveIntegerField(help_text='Período académico (1=PA I … 8=PA VIII)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden dentro del período para la presentación visual')),
                ('curricular_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_plans', to='curriculum.curricularunit', verbose_name='Unidad Curricular')),
            ],
            options={
                'verbose_name': 'Ítem del Plan Curricular',
                'verbose_name_plural': 'Plan Curricular',
                'ordering': ['career_id', 'academic_period', 'order', 'curricular_unit__name'],
                'unique_together': {('career_id', 'curricular_unit', 'academic_period')},
            },
        ),
        migrations.CreateModel(
            name='CareerNucleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_id', models.IntegerField(db_index=True, help_text='ID Carrera (students_service)')),
                ('nucleo_id', models.IntegerField(db_index=True, help_text='ID Núcleo (auth_service)')),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by_id', models.IntegerField(blank=True, help_text='ID del usuario global que realizó la asignación (auth_service)', null=True)),
            ],
            options={
                'verbose_name': 'Carrera en Núcleo',
                'verbose_name_plural': 'Carreras por Núcleo',
                'ordering': ['career_id', 'nucleo_id'],
                'unique_together': {('career_id', 'nucleo_id')},
            },
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_plan_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='curriculum.careerplan', verbose_name='Ítem del plan que tiene la prelación')),
                ('required_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_prerequisite_for', to='curriculum.curricularunit', verbose_name='UC requerida (prelación)')),
            ],
            options={
                'verbose_name': 'Prelación',
                'verbose_name_plural': 'Prelaciones',
                'unique_together': {('career_plan_item', 'required_unit')},
            },
        ),
    ]
