# Generated by Django 5.2.12 on 2026-03-10 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurricularUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Código institucional (ej: UC-CFD-001). Se auto-genera si queda vacío.', max_length=20, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('component', models.CharField(choices=[('CFPE', 'Formación Profesional Específico'), ('CFD', 'Formación Docente'), ('CFC', 'Formación Contextualizado'), ('ECU', 'Eje Curricular')], max_length=10)),
                ('uc_type', models.CharField(choices=[('UNCO', 'Obligatoria'), ('UNCLE', 'Libre Elección')], default='UNCO', max_length=10, verbose_name='Tipo')),
                ('level', models.CharField(blank=True, choices=[('FUND', 'Fundamentación'), ('INTEG', 'Integración'), ('PROF', 'Profundización'), ('', 'No especificado')], max_length=10, verbose_name='Nivel')),
                ('area', models.CharField(blank=True, help_text='Área temática (ej: Formación Ciudadana)', max_length=200)),
                ('credits', models.PositiveIntegerField(default=4, verbose_name='Créditos (CA)')),
                ('teaching_hours', models.PositiveIntegerField(default=4, verbose_name='Horas Docente (HAD)')),
                ('student_hours', models.PositiveIntegerField(default=8, verbose_name='Horas Estudiante (HLE)')),
                ('is_exit_req', models.BooleanField(default=False, verbose_name='Requisito de Egreso (AE/SC)')),
                ('description', models.TextField(blank=True, verbose_name='Descripción / Fundamentación')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unidad Curricular',
                'verbose_name_plural': 'Unidades Curriculares',
                'ordering': ['component', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CareerPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_period', models.PositiveIntegerField(help_text='Período académico (1=PA I … 8=PA VIII)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden dentro del período para la presentación visual')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curricular_plans', to='students.career', verbose_name='Carrera')),
                ('curricular_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_plans', to='curriculum.curricularunit', verbose_name='Unidad Curricular')),
            ],
            options={
                'verbose_name': 'Ítem del Plan Curricular',
                'verbose_name_plural': 'Plan Curricular',
                'ordering': ['career', 'academic_period', 'order', 'curricular_unit__name'],
                'unique_together': {('career', 'curricular_unit', 'academic_period')},
            },
        ),
        migrations.CreateModel(
            name='CareerNucleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='career_nucleos_assigned', to=settings.AUTH_USER_MODEL)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nucleos', to='students.career')),
                ('nucleo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='core.nucleo')),
            ],
            options={
                'verbose_name': 'Carrera en Núcleo',
                'verbose_name_plural': 'Carreras por Núcleo',
                'ordering': ['career', 'nucleo'],
                'unique_together': {('career', 'nucleo')},
            },
        ),
        migrations.CreateModel(
            name='CareerSede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='career_sedes_assigned', to=settings.AUTH_USER_MODEL)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes', to='students.career')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='core.sede')),
            ],
            options={
                'verbose_name': 'Carrera en Sede',
                'verbose_name_plural': 'Carreras por Sede',
                'ordering': ['career', 'sede'],
                'unique_together': {('career', 'sede')},
            },
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_plan_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='curriculum.careerplan', verbose_name='Ítem del plan que tiene la prelación')),
                ('required_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_prerequisite_for', to='curriculum.curricularunit', verbose_name='UC requerida (prelación)')),
            ],
            options={
                'verbose_name': 'Prelación',
                'verbose_name_plural': 'Prelaciones',
                'unique_together': {('career_plan_item', 'required_unit')},
            },
        ),
    ]
