# Generated by Django 5.2.12 on 2026-03-10 20:13

import core.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nucleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del núcleo')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Núcleo',
                'verbose_name_plural': 'Núcleos',
                'ordering': ['sede__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la sede')),
                ('sigla', models.CharField(blank=True, help_text='Ej: IPB, IPM, Rectorado', max_length=20, verbose_name='Sigla')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del rol')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rol del Sistema',
                'verbose_name_plural': 'Roles del Sistema',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(default='Sistema Universitario', max_length=200, verbose_name='Nombre del sistema')),
                ('university_name', models.CharField(default='Mi Universidad', max_length=200, verbose_name='Nombre de la universidad')),
                ('primary_color', models.CharField(default='#1a237e', max_length=7, verbose_name='Color primario (hex)')),
                ('secondary_color', models.CharField(default='#283593', max_length=7, verbose_name='Color secundario (hex)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo de la universidad')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuración del Sistema',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('code', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='Código de usuario')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('student', 'Estudiante'), ('professor', 'Profesor'), ('aspirant', 'Aspirante'), ('control_estudios', 'Control de Estudios'), ('docencia', 'Coordinación Docente'), ('secretaria', 'Secretaría'), ('otro', 'Otro / Personalizado')], default='student', max_length=20, verbose_name='Rol')),
                ('can_access_django_admin', models.BooleanField(default=False, help_text='Otorga acceso al panel técnico en /system-admin/. Solo debe asignarse a personal técnico de TI. Los superusuarios siempre tienen acceso independientemente de este campo.', verbose_name='Acceso al panel técnico')),
                ('scope_level', models.CharField(choices=[('global', 'Rectorado / Global'), ('sede', 'Sede'), ('nucleo', 'Núcleo')], default='global', help_text='Define qué datos puede ver este usuario: global=todo, sede=su sede, núcleo=solo su núcleo.', max_length=10, verbose_name='Nivel organizacional')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('scope_nucleo', models.ForeignKey(blank=True, help_text='Obligatorio cuando el nivel es "Núcleo".', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.nucleo', verbose_name='Núcleo asignado')),
                ('scope_sede', models.ForeignKey(blank=True, help_text='Obligatorio cuando el nivel es "Sede" o "Núcleo".', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.sede', verbose_name='Sede asignada')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Aspirant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código de aspirante')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('national_id', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Cédula / Documento de identidad')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('career_id', models.IntegerField(blank=True, null=True, verbose_name='ID 1ª carrera deseada')),
                ('career_name', models.CharField(blank=True, max_length=200, verbose_name='1ª Carrera deseada')),
                ('career_id_2', models.IntegerField(blank=True, null=True, verbose_name='ID 2ª carrera deseada')),
                ('career_name_2', models.CharField(blank=True, max_length=200, verbose_name='2ª Carrera deseada')),
                ('career_id_3', models.IntegerField(blank=True, null=True, verbose_name='ID 3ª carrera deseada')),
                ('career_name_3', models.CharField(blank=True, max_length=200, verbose_name='3ª Carrera deseada')),
                ('admission_type', models.CharField(choices=[('ordinario', 'Admisión Ordinaria'), ('convalidacion', 'Convalidación de Estudios'), ('traslado_interno', 'Traslado Interno'), ('traslado_externo', 'Traslado Externo'), ('reingreso', 'Reingreso')], default='ordinario', max_length=20, verbose_name='Tipo de admisión')),
                ('prev_institution', models.CharField(blank=True, max_length=300, verbose_name='Institución de procedencia')),
                ('prev_career', models.CharField(blank=True, max_length=300, verbose_name='Carrera/Programa cursado')),
                ('prev_degree', models.CharField(blank=True, max_length=100, verbose_name='Título/Grado obtenido')),
                ('prev_graduation_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Año de egreso/retiro')),
                ('origin_carnet', models.CharField(blank=True, help_text='Carnet en la sede/institución de procedencia (traslado) o carnet anterior (reingreso).', max_length=30, verbose_name='Carnet de origen')),
                ('last_semester_completed', models.PositiveSmallIntegerField(blank=True, help_text='Semestre en el que quedó al momento del traslado o retiro.', null=True, verbose_name='Último semestre aprobado')),
                ('reinstatement_reason', models.TextField(blank=True, help_text='Explica brevemente el motivo por el que dejó de estudiar y por qué desea reingresar.', verbose_name='Motivo del reingreso')),
                ('admission_status', models.CharField(choices=[('pending', 'Pendiente'), ('in_review', 'En revisión'), ('approved', 'Admitido'), ('rejected', 'No admitido'), ('waitlisted', 'En lista de espera'), ('accepted', 'Aceptado por el Aspirante'), ('declined', 'Rechazado por el Aspirante')], default='pending', max_length=20, verbose_name='Estado de admisión')),
                ('admitted_career_id', models.IntegerField(blank=True, null=True, verbose_name='ID carrera admitida')),
                ('admitted_career_name', models.CharField(blank=True, max_length=200, verbose_name='Carrera admitida')),
                ('admitted_option', models.PositiveSmallIntegerField(blank=True, help_text='1=primera opción, 2=segunda opción, 3=tercera opción seleccionada por el aspirante.', null=True, verbose_name='Opción admitida')),
                ('admission_notes', models.TextField(blank=True, verbose_name='Observaciones de admisión')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=20, verbose_name='Estado')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_aspirants', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aspirant_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del sistema')),
                ('nucleo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aspirants', to='core.nucleo', verbose_name='Núcleo')),
                ('origin_sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aspirants_traslado', to='core.sede', verbose_name='Sede de origen (traslado interno)')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aspirants', to='core.sede', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Aspirante',
                'verbose_name_plural': 'Aspirantes',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código de solicitud')),
                ('student_carnet', models.CharField(blank=True, max_length=30, verbose_name='Carnet')),
                ('student_career', models.CharField(blank=True, max_length=200, verbose_name='Carrera')),
                ('student_semester', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Semestre')),
                ('cert_type', models.CharField(choices=[('constancia_estudios', 'Constancia de Estudios'), ('record_notas', 'Récord Académico (constancia de notas)'), ('constancia_egresado', 'Constancia de Egresado'), ('buena_conducta', 'Constancia de Buena Conducta'), ('carga_academica', 'Constancia de Carga Académica'), ('otro', 'Otro tipo de constancia')], max_length=30, verbose_name='Tipo de constancia')),
                ('purpose', models.CharField(choices=[('beca', 'Solicitud de beca'), ('empleo', 'Trámites de empleo / empleador'), ('pasaporte', 'Trámites de pasaporte / visado'), ('banco', 'Trámites bancarios'), ('postgrado', 'Admisión a postgrado'), ('legal', 'Trámites legales / judiciales'), ('personal', 'Uso personal'), ('otro', 'Otro propósito')], max_length=30, verbose_name='Propósito')),
                ('copies', models.PositiveSmallIntegerField(default=1, help_text='Cuántas copias físicas necesita.', verbose_name='Número de copias')),
                ('period_ref', models.CharField(blank=True, help_text='Ej: "Lapso I 2025" o dejar vacío para el período actual.', max_length=100, verbose_name='Período de referencia')),
                ('student_notes', models.TextField(blank=True, help_text='Indicaciones adicionales para Control de Estudios.', verbose_name='Observaciones del estudiante')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de revisión'), ('processing', 'En proceso'), ('ready', 'Lista para retirar'), ('delivered', 'Entregada'), ('rejected', 'Rechazada')], default='pending', max_length=20, verbose_name='Estado')),
                ('staff_notes', models.TextField(blank=True, help_text='Observaciones internas — el estudiante puede verlas.', verbose_name='Notas del personal')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de proceso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_certificates', to=settings.AUTH_USER_MODEL, verbose_name='Procesado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_requests', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Solicitud de Constancia',
                'verbose_name_plural': 'Solicitudes de Constancias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConvalidacionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_subject_name', models.CharField(max_length=300, verbose_name='Asignatura (institución de origen)')),
                ('origin_subject_code', models.CharField(blank=True, max_length=50, verbose_name='Código (origen)')),
                ('origin_credits', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Unidades crédito (origen)')),
                ('origin_hours', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Horas académicas (origen)')),
                ('origin_grade', models.CharField(blank=True, help_text='Tal como aparece en el record: 18/20, A, 4.0, etc.', max_length=20, verbose_name='Calificación obtenida')),
                ('origin_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Año en que cursó la asignatura')),
                ('upel_course_id', models.IntegerField(blank=True, null=True, verbose_name='ID UC UPEL')),
                ('upel_course_name', models.CharField(blank=True, max_length=300, verbose_name='Unidad Curricular UPEL')),
                ('upel_course_code', models.CharField(blank=True, max_length=50, verbose_name='Código UC UPEL')),
                ('upel_credits', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Unidades crédito UPEL')),
                ('status', models.CharField(choices=[('solicitada', 'Solicitada'), ('en_revision', 'En revisión — Comisión'), ('prueba_requerida', 'Prueba de suficiencia requerida'), ('convalidada', 'Convalidada ✓'), ('no_convalidada', 'No convalidada ✗'), ('convalidada_condicion', 'Convalidada con condición')], default='solicitada', max_length=25, verbose_name='Estado')),
                ('committee_notes', models.TextField(blank=True, verbose_name='Observaciones de la Comisión de Convalidaciones')),
                ('evaluated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de evaluación')),
                ('council_resolution', models.CharField(blank=True, help_text='Ej: CD-0045-2026', max_length=100, verbose_name='Nro. Resolución — Consejo Directivo')),
                ('council_resolution_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Resolución CD')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aspirant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convalidacion_items', to='core.aspirant', verbose_name='Aspirante')),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_convalidaciones', to=settings.AUTH_USER_MODEL, verbose_name='Evaluado por')),
            ],
            options={
                'verbose_name': 'Item de Convalidación',
                'verbose_name_plural': 'Items de Convalidación',
                'ordering': ['aspirant', 'origin_subject_name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('cedula', 'Cédula de Identidad'), ('titulo', 'Título Universitario'), ('notas_cert', 'Notas Certificadas / Récord Académico'), ('foto', 'Fotografía tipo carnet'), ('partida', 'Partida de Nacimiento'), ('cv', 'Currículum Vitae'), ('carta_motivos', 'Carta de Exposición de Motivos'), ('buena_conducta', 'Carta / Declaración de Buena Conducta'), ('recomendacion', 'Carta de Recomendación'), ('constancia_trab', 'Constancia de Trabajo'), ('record_prev', 'Récord Académico (institución de origen)'), ('titulo_prev', 'Título de institución de origen'), ('comprobante_pago', 'Comprobante de Pago de Arancel'), ('otro', 'Otro Documento')], max_length=30, verbose_name='Tipo de documento')),
                ('file', models.FileField(upload_to=core.models.aspirant_doc_upload_path, verbose_name='Archivo')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Nombre original del archivo')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Tamaño (bytes)')),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name='Observaciones')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Subido el')),
                ('aspirant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.aspirant', verbose_name='Aspirante')),
            ],
            options={
                'verbose_name': 'Documento del Expediente',
                'verbose_name_plural': 'Documentos del Expediente',
                'ordering': ['aspirant', 'doc_type'],
            },
        ),
        migrations.AddField(
            model_name='nucleo',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nucleos', to='core.sede', verbose_name='Sede'),
        ),
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Dra. María García', max_length=200, verbose_name='Nombre completo')),
                ('position', models.CharField(help_text='Ej: Rector, Vicerrector Académico, Secretario', max_length=200, verbose_name='Cargo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.IntegerField(default=0, help_text='Orden de aparición en documentos', verbose_name='Orden')),
                ('sede', models.ForeignKey(blank=True, help_text='Dejar en blanco si es autoridad de Rectorado (nacional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorities', to='core.sede', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Autoridad',
                'verbose_name_plural': 'Autoridades',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('auth', 'Autenticación / Usuarios'), ('students', 'Estudiantes'), ('courses', 'Cursos'), ('enrollments', 'Inscripciones'), ('grades', 'Calificaciones'), ('settings', 'Configuración del Sistema')], max_length=50, verbose_name='Servicio')),
                ('action', models.CharField(choices=[('view', 'Ver'), ('create', 'Crear'), ('edit', 'Editar'), ('delete', 'Eliminar')], max_length=50, verbose_name='Acción')),
                ('allowed', models.BooleanField(default=True, verbose_name='Permitido')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='core.systemrole', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Permiso de Rol',
                'verbose_name_plural': 'Permisos de Roles',
                'unique_together': {('role', 'service', 'action')},
            },
        ),
    ]
