# Generated by Django 4.2 on 2026-03-02 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del rol')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rol del Sistema',
                'verbose_name_plural': 'Roles del Sistema',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(default='Sistema Universitario', max_length=200, verbose_name='Nombre del sistema')),
                ('university_name', models.CharField(default='Mi Universidad', max_length=200, verbose_name='Nombre de la universidad')),
                ('primary_color', models.CharField(default='#1a237e', max_length=7, verbose_name='Color primario (hex)')),
                ('secondary_color', models.CharField(default='#283593', max_length=7, verbose_name='Color secundario (hex)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo de la universidad')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuración del Sistema',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='Código de usuario'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('student', 'Estudiante'), ('professor', 'Profesor'), ('aspirant', 'Aspirante')], default='student', max_length=20, verbose_name='Rol'),
        ),
        migrations.CreateModel(
            name='Aspirant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código de aspirante')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('national_id', models.CharField(max_length=30, unique=True, verbose_name='Cédula / Documento de identidad')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=20, verbose_name='Estado')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aspirant_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del sistema')),
            ],
            options={
                'verbose_name': 'Aspirante',
                'verbose_name_plural': 'Aspirantes',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('auth', 'Autenticación / Usuarios'), ('students', 'Estudiantes'), ('courses', 'Cursos'), ('enrollments', 'Inscripciones'), ('grades', 'Calificaciones'), ('settings', 'Configuración del Sistema')], max_length=50, verbose_name='Servicio')),
                ('action', models.CharField(choices=[('view', 'Ver'), ('create', 'Crear'), ('edit', 'Editar'), ('delete', 'Eliminar')], max_length=50, verbose_name='Acción')),
                ('allowed', models.BooleanField(default=True, verbose_name='Permitido')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='core.systemrole', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Permiso de Rol',
                'verbose_name_plural': 'Permisos de Roles',
                'unique_together': {('role', 'service', 'action')},
            },
        ),
    ]
