# Generated by Django 4.2 on 2026-03-02 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_systemrole_systemsettings_customuser_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la sede')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='aspirant',
            name='national_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Cédula / Documento de identidad'),
        ),
        migrations.CreateModel(
            name='Nucleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del núcleo')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nucleos', to='core.sede', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Núcleo',
                'verbose_name_plural': 'Núcleos',
                'ordering': ['sede__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='aspirant',
            name='nucleo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aspirants', to='core.nucleo', verbose_name='Núcleo'),
        ),
        migrations.AddField(
            model_name='aspirant',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aspirants', to='core.sede', verbose_name='Sede'),
        ),
    ]
