# Generated by Django 4.2 on 2026-03-02 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customuser_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='scope_level',
            field=models.CharField(choices=[('global', 'Rectorado / Global'), ('sede', 'Sede'), ('nucleo', 'Núcleo')], default='global', help_text='Define qué datos puede ver este usuario: global=todo, sede=su sede, núcleo=solo su núcleo.', max_length=10, verbose_name='Nivel organizacional'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='scope_nucleo',
            field=models.ForeignKey(blank=True, help_text='Obligatorio cuando el nivel es "Núcleo".', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.nucleo', verbose_name='Núcleo asignado'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='scope_sede',
            field=models.ForeignKey(blank=True, help_text='Obligatorio cuando el nivel es "Sede" o "Núcleo".', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.sede', verbose_name='Sede asignada'),
        ),
    ]
