# Generated by Django 4.2 on 2026-03-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_customuser_scope_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_access_django_admin',
            field=models.BooleanField(default=False, help_text='Otorga acceso al panel técnico en /system-admin/. Solo debe asignarse a personal técnico de TI. Los superusuarios siempre tienen acceso independientemente de este campo.', verbose_name='Acceso al panel técnico'),
        ),
    ]
