# Generated by Django 4.2 on 2026-03-03 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_customuser_can_access_django_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirant',
            name='admission_notes',
            field=models.TextField(blank=True, verbose_name='Observaciones de admisión'),
        ),
        migrations.AddField(
            model_name='aspirant',
            name='admission_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('in_review', 'En revisión'), ('approved', 'Admitido'), ('rejected', 'No admitido'), ('waitlisted', 'En lista de espera')], default='pending', max_length=20, verbose_name='Estado de admisión'),
        ),
        migrations.AddField(
            model_name='aspirant',
            name='admitted_career_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID carrera admitida'),
        ),
        migrations.AddField(
            model_name='aspirant',
            name='admitted_career_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Carrera admitida'),
        ),
        migrations.AddField(
            model_name='aspirant',
            name='admitted_option',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1=primera opción, 2=segunda opción, 3=tercera opción seleccionada por el aspirante.', null=True, verbose_name='Opción admitida'),
        ),
        migrations.AddField(
            model_name='aspirant',
            name='career_id_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID 2ª carrera deseada'),
        ),
        migrations.AddField(
            model_name='aspirant',
            name='career_id_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID 3ª carrera deseada'),
        ),
        migrations.AddField(
            model_name='aspirant',
            name='career_name_2',
            field=models.CharField(blank=True, max_length=200, verbose_name='2ª Carrera deseada'),
        ),
        migrations.AddField(
            model_name='aspirant',
            name='career_name_3',
            field=models.CharField(blank=True, max_length=200, verbose_name='3ª Carrera deseada'),
        ),
        migrations.AddField(
            model_name='aspirant',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión'),
        ),
        migrations.AddField(
            model_name='aspirant',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_aspirants', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por'),
        ),
        migrations.AlterField(
            model_name='aspirant',
            name='career_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID 1ª carrera deseada'),
        ),
        migrations.AlterField(
            model_name='aspirant',
            name='career_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='1ª Carrera deseada'),
        ),
    ]
