# Generated by Django 4.2 on 2026-03-03 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_documentattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirant',
            name='last_semester_completed',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Semestre en el que quedó al momento del traslado o retiro.', null=True, verbose_name='Último semestre aprobado'),
        ),
        migrations.AddField(
            model_name='aspirant',
            name='origin_carnet',
            field=models.CharField(blank=True, help_text='Carnet en la sede/institución de procedencia (traslado) o carnet anterior (reingreso).', max_length=30, verbose_name='Carnet de origen'),
        ),
        migrations.AddField(
            model_name='aspirant',
            name='origin_sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aspirants_traslado', to='core.sede', verbose_name='Sede de origen (traslado interno)'),
        ),
        migrations.AddField(
            model_name='aspirant',
            name='reinstatement_reason',
            field=models.TextField(blank=True, help_text='Explica brevemente el motivo por el que dejó de estudiar y por qué desea reingresar.', verbose_name='Motivo del reingreso'),
        ),
        migrations.AlterField(
            model_name='aspirant',
            name='admission_type',
            field=models.CharField(choices=[('ordinario', 'Admisión Ordinaria'), ('convalidacion', 'Convalidación de Estudios'), ('traslado_interno', 'Traslado Interno'), ('traslado_externo', 'Traslado Externo'), ('reingreso', 'Reingreso')], default='ordinario', max_length=20, verbose_name='Tipo de admisión'),
        ),
    ]
