# Generated by Django 4.2 on 2026-03-03 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_aspirant_admission_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código de solicitud')),
                ('student_carnet', models.CharField(blank=True, max_length=30, verbose_name='Carnet')),
                ('student_career', models.CharField(blank=True, max_length=200, verbose_name='Carrera')),
                ('student_semester', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Semestre')),
                ('cert_type', models.CharField(choices=[('constancia_estudios', 'Constancia de Estudios'), ('record_notas', 'Récord Académico (constancia de notas)'), ('constancia_egresado', 'Constancia de Egresado'), ('buena_conducta', 'Constancia de Buena Conducta'), ('carga_academica', 'Constancia de Carga Académica'), ('otro', 'Otro tipo de constancia')], max_length=30, verbose_name='Tipo de constancia')),
                ('purpose', models.CharField(choices=[('beca', 'Solicitud de beca'), ('empleo', 'Trámites de empleo / empleador'), ('pasaporte', 'Trámites de pasaporte / visado'), ('banco', 'Trámites bancarios'), ('postgrado', 'Admisión a postgrado'), ('legal', 'Trámites legales / judiciales'), ('personal', 'Uso personal'), ('otro', 'Otro propósito')], max_length=30, verbose_name='Propósito')),
                ('copies', models.PositiveSmallIntegerField(default=1, help_text='Cuántas copias físicas necesita.', verbose_name='Número de copias')),
                ('period_ref', models.CharField(blank=True, help_text='Ej: "Lapso I 2025" o dejar vacío para el período actual.', max_length=100, verbose_name='Período de referencia')),
                ('student_notes', models.TextField(blank=True, help_text='Indicaciones adicionales para Control de Estudios.', verbose_name='Observaciones del estudiante')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de revisión'), ('processing', 'En proceso'), ('ready', 'Lista para retirar'), ('delivered', 'Entregada'), ('rejected', 'Rechazada')], default='pending', max_length=20, verbose_name='Estado')),
                ('staff_notes', models.TextField(blank=True, help_text='Observaciones internas — el estudiante puede verlas.', verbose_name='Notas del personal')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de proceso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_certificates', to=settings.AUTH_USER_MODEL, verbose_name='Procesado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_requests', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Solicitud de Constancia',
                'verbose_name_plural': 'Solicitudes de Constancias',
                'ordering': ['-created_at'],
            },
        ),
    ]
