# Generated by Django 4.2 on 2026-03-09 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_certificaterequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Dra. María García', max_length=200, verbose_name='Nombre completo')),
                ('position', models.CharField(help_text='Ej: Rector, Vicerrector Académico, Secretario', max_length=200, verbose_name='Cargo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.IntegerField(default=0, help_text='Orden de aparición en documentos', verbose_name='Orden')),
                ('sede', models.ForeignKey(blank=True, help_text='Dejar en blanco si es autoridad de Rectorado (nacional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorities', to='core.sede', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Autoridad',
                'verbose_name_plural': 'Autoridades',
                'ordering': ['order', 'name'],
            },
        ),
    ]
