# Generated by Django 4.2 on 2026-03-10 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_authority'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='sigla',
            field=models.CharField(blank=True, help_text='Ej: IPB, IPM, Rectorado', max_length=20, verbose_name='Sigla'),
        ),
    ]
