# Generated by Django 4.2 on 2026-03-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_sede_sigla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirant',
            name='admission_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('in_review', 'En revisión'), ('approved', 'Admitido'), ('rejected', 'No admitido'), ('waitlisted', 'En lista de espera'), ('accepted', 'Aceptado por el Aspirante'), ('declined', 'Rechazado por el Aspirante')], default='pending', max_length=20, verbose_name='Estado de admisión'),
        ),
    ]
